---
- hosts: all
  remote_user: vagrant
  tasks:
  - apt: update_cache=yes
  - apt_repository: repo='deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main' state=present
  - apt_repository: repo='deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe' state=present
  # - apt: upgrade=dist update_cache=yes
  - apt: name=imagemagick state=present
  - apt: name=php5-imagick state=present
